language: node_js
node_js: "8"
services:
  - mysql
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
  # need to tell travis fake db to use password for root user.
  # - mysql -e 'ALTER USER "root"@"localhost" IDENTIFIED BY "password";'
  
